// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SimCenter.Infrastructure.Persistence;

#nullable disable

namespace SimCenter.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SimCenter.Domain.Entities.DrivingSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("GameCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("game_code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("session_type");

                    b.Property<Guid>("SimRigId")
                        .HasColumnType("uuid")
                        .HasColumnName("sim_rig_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_driving_sessions");

                    b.HasIndex("SimRigId")
                        .IsUnique()
                        .HasDatabaseName("ix_driving_sessions_sim_rig_id")
                        .HasFilter("status = 'Active'");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_driving_sessions_user_id");

                    b.HasIndex("SimRigId", "Status", "StartedAt")
                        .HasDatabaseName("ix_driving_sessions_sim_rig_id_status_started_at");

                    b.ToTable("driving_sessions", (string)null);
                });

            modelBuilder.Entity("SimCenter.Domain.Entities.Lap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DrivingSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("driving_session_id");

                    b.Property<string>("GameCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("game_code");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsInvalidatedManually")
                        .HasColumnType("boolean")
                        .HasColumnName("is_invalidated_manually");

                    b.Property<bool>("IsRankingEligible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ranking_eligible");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean")
                        .HasColumnName("is_valid");

                    b.Property<int>("LapNumber")
                        .HasColumnType("integer")
                        .HasColumnName("lap_number");

                    b.Property<int>("LapTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("lap_time_ms");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("session_type");

                    b.Property<DateTime>("SetAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("set_at");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uuid")
                        .HasColumnName("track_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_laps");

                    b.HasIndex("DrivingSessionId")
                        .HasDatabaseName("ix_laps_driving_session_id");

                    b.HasIndex("TrackId", "LapTimeMs")
                        .HasDatabaseName("ix_laps_track_id_lap_time_ms")
                        .HasFilter("is_ranking_eligible = true");

                    b.HasIndex("UserId", "TrackId", "LapTimeMs")
                        .HasDatabaseName("ix_laps_user_id_track_id_lap_time_ms");

                    b.HasIndex("TrackId", "GameCode", "SessionType", "IsRankingEligible", "SetAt")
                        .HasDatabaseName("ix_laps_track_id_game_code_session_type_is_ranking_eligible_se");

                    b.ToTable("laps", (string)null);
                });

            modelBuilder.Entity("SimCenter.Domain.Entities.LapSector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("LapId")
                        .HasColumnType("uuid")
                        .HasColumnName("lap_id");

                    b.Property<int>("SectorNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sector_number");

                    b.Property<int>("SectorTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("sector_time_ms");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_lap_sectors");

                    b.HasIndex("LapId", "SectorNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_lap_sectors_lap_id_sector_number");

                    b.ToTable("lap_sectors", (string)null);
                });

            modelBuilder.Entity("SimCenter.Domain.Entities.SimRig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("RigCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("rig_code");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("store_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sim_rigs");

                    b.HasIndex("RigCode")
                        .IsUnique()
                        .HasDatabaseName("ix_sim_rigs_rig_code");

                    b.HasIndex("StoreId")
                        .HasDatabaseName("ix_sim_rigs_store_id");

                    b.ToTable("sim_rigs", (string)null);
                });

            modelBuilder.Entity("SimCenter.Domain.Entities.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_stores");

                    b.ToTable("stores", (string)null);
                });

            modelBuilder.Entity("SimCenter.Domain.Entities.Track", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GameCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("game_code");

                    b.Property<int>("GameTrackId")
                        .HasColumnType("integer")
                        .HasColumnName("game_track_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tracks");

                    b.HasIndex("GameCode", "GameTrackId")
                        .IsUnique()
                        .HasDatabaseName("ix_tracks_game_code_game_track_id");

                    b.ToTable("tracks", (string)null);
                });

            modelBuilder.Entity("SimCenter.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SimCenter.Domain.Entities.DrivingSession", b =>
                {
                    b.HasOne("SimCenter.Domain.Entities.SimRig", "SimRig")
                        .WithMany()
                        .HasForeignKey("SimRigId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_driving_sessions_sim_rigs_sim_rig_id");

                    b.HasOne("SimCenter.Domain.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_driving_sessions_users_user_id");

                    b.Navigation("SimRig");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SimCenter.Domain.Entities.Lap", b =>
                {
                    b.HasOne("SimCenter.Domain.Entities.DrivingSession", "DrivingSession")
                        .WithMany("Laps")
                        .HasForeignKey("DrivingSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_laps_driving_sessions_driving_session_id");

                    b.HasOne("SimCenter.Domain.Entities.Track", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_laps_tracks_track_id");

                    b.Navigation("DrivingSession");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("SimCenter.Domain.Entities.LapSector", b =>
                {
                    b.HasOne("SimCenter.Domain.Entities.Lap", "Lap")
                        .WithMany("Sectors")
                        .HasForeignKey("LapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lap_sectors_laps_lap_id");

                    b.Navigation("Lap");
                });

            modelBuilder.Entity("SimCenter.Domain.Entities.SimRig", b =>
                {
                    b.HasOne("SimCenter.Domain.Entities.Store", "Store")
                        .WithMany("Rigs")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sim_rigs_stores_store_id");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("SimCenter.Domain.Entities.DrivingSession", b =>
                {
                    b.Navigation("Laps");
                });

            modelBuilder.Entity("SimCenter.Domain.Entities.Lap", b =>
                {
                    b.Navigation("Sectors");
                });

            modelBuilder.Entity("SimCenter.Domain.Entities.Store", b =>
                {
                    b.Navigation("Rigs");
                });

            modelBuilder.Entity("SimCenter.Domain.Entities.User", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
